// import { Inter } from "next/font/google";


import SideBar from "../../../components/sidebar";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>

//         <SideBar>

//         {children}
//         </SideBar>
//       </body>
//     </html>
//   );
// }

export default function DashboardLayout({
  children, // will be a page or nested layout
}) {
  return (
    <section>
      <SideBar>
        {children}
      </SideBar>
    </section>
  );
}
